name: schedule-smoke
on:
  schedule:
    - cron: "3-59/5 * * * *"
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: echo "event=${{ github.event_name }} at $(date -u) UTC"
